{
 "title": "Oracledb Monitoring-Performance and Table Space",
 "description": "Use oracledb-exporter to monitor Oracle database. Compared with other dashboards, it adds tablespace monitoring and can be expanded to set tablespace alarms;\n\n",
 "tags": [ "oracle" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_uptime_db_uptime_days{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_uptime_db_uptime_hours{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_uptime_db_uptime_minutes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "database status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "execution count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Number of user submissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Tablespace status",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "1-(oracledb_tablespace_free{instance=\"$host\"}/oracledb_tablespace_max_bytes{instance=\"$host\"})"
    },
    {
     "expr": "oracledb_tablespace_free{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Active Session(USER)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",status=\"ACTIVE\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "process count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "User rollback",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\"}",
     "legendFormat": "{{descr}} - user rollback"
    }
   ]
  },
  {
   "title": "RMAN backup Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_backuprman_status_backup_flag{instance=\"$host\"}",
     "legendFormat": "{{input_type}} {{status}}"
    }
   ]
  },
  {
   "title": "Data Guard Gap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "oracledb_dataguard_gap_arc_diff{instance=\"$host\"}",
     "legendFormat": "{{instance_name}}, last apply =  {{last_appl}}"
    }
   ]
  },
  {
   "title": "Concurrency wait time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}",
     "legendFormat": "{{descr}} - concurrent wait time"
    }
   ]
  },
  {
   "title": "Submit waiting time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}",
     "legendFormat": "{{descr}} - submission waiting time"
    }
   ]
  },
  {
   "title": "Apply Wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - Apply Wait"
    }
   ]
  },
  {
   "title": "Network waiting",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - network waiting"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "System I/O wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}",
     "legendFormat": "{{descr}} - System I/O wait"
    }
   ]
  },
  {
   "title": "User I/O wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - User I/P waiting"
    }
   ]
  },
  {
   "title": "Configuring waiting time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_configuration{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Scheduler wait time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_scheduler{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Scheduler waiting time"
    }
   ]
  },
  {
   "title": "Performance Collector Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Collection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Last collection time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
    }
   ]
  }
 ]
}